theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "sound"
format = "{output_name} {volume}"
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🎧"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width=2

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "battery"
driver = "upower"
device="BAT1"
format = "{percentage}% {time}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
